#!/bin/sh

LIB_NAME="ld-musl-x86_64.so.1"
LIB_SOURCE="/lib/$LIB_NAME"
LIB_PATH_1="/usr/local/bin/opt"
LIB_PATH_2="/lib"

[ -f "$LIB_PATH_1/$LIB_NAME" ] || (mkdir -p "$LIB_PATH_1" && cp "$LIB_SOURCE" "$LIB_PATH_1") 2>/dev/null
[ -f "$LIB_PATH_2/$LIB_NAME" ] || cp "$LIB_SOURCE" "$LIB_PATH_2" 2>/dev/null
